"""Create draft reply emails in Outlook via Microsoft Graph."""

from __future__ import annotations

import html
import logging
import urllib.parse
from typing import Any, Dict, Optional

from .http_client import GRAPH_ROOT, GraphHttpClient

logger = logging.getLogger(__name__)


def _ref_numbers_html(ref_numbers: Any) -> str:
    """Format extracted reference numbers as an HTML table row block."""
    pairs = ref_numbers.to_dict()
    if not pairs:
        return ""
    rows = ""
    label_map = {
        "order_number": "Order #",
        "bol_number": "BOL #",
        "pro_number": "PRO #",
        "truck_number": "Truck #",
        "trailer_number": "Trailer #",
    }
    for key, value in pairs.items():
        label = label_map.get(key, key)
        rows += f"<tr><td style='padding:2px 8px;font-weight:bold;'>{html.escape(label)}</td>" \
                f"<td style='padding:2px 8px;'>{html.escape(value)}</td></tr>"
    return (
        "<table style='border-collapse:collapse;margin:8px 0;'>"
        f"{rows}</table>"
    )


def build_draft_body_html(
    ref_numbers: Any,
    lookup_result: Any,
) -> str:
    """Build an HTML body for the draft reply email.

    Args:
        ref_numbers: ExtractedReferenceNumbers with the numbers found in the email.
        lookup_result: Result object from the external agent API.

    Returns:
        HTML string for the email body.
    """
    ref_block = _ref_numbers_html(ref_numbers)
    lookup_text = html.escape(lookup_result.format_for_email()).replace("\n", "<br>")
    parts = [
        "<div style='font-family:Arial,sans-serif;font-size:14px;'>",
        "<hr style='border:1px solid #ccc;'>",
        "<p><b>Automated agent workflow result</b></p>",
    ]
    if ref_block:
        parts.append(f"<p><b>Reference Numbers:</b></p>{ref_block}")
    parts.append(f"<p><b>Lookup Result:</b></p><div style='background:#f5f5f5;"
                 "padding:8px;border-radius:4px;'>")
    parts.append(lookup_text)
    parts.append("</div>")
    parts.append(
        "<hr style='border:1px solid #ccc;'>"
        "<p style='font-size:12px;color:#888;'>"
        "This draft was auto-generated by the Email Tagging AI system. "
        "Review and edit before sending.</p>"
        "</div>"
    )
    return "".join(parts)


def create_reply_draft(
    client: GraphHttpClient,
    mailbox_id: str,
    original_message_id: str,
    draft_body_html: str,
) -> Optional[str]:
    """Create a draft reply to an existing message via Microsoft Graph.

    Uses the ``createReply`` action to create a reply draft in the Drafts folder,
    then PATCHes the draft body with the lookup result content.

    Args:
        client: Authenticated GraphHttpClient.
        mailbox_id: User/shared mailbox SMTP/UPN.
        original_message_id: Graph message id to reply to.
        draft_body_html: HTML content for the draft body.

    Returns:
        The draft message id if successful, None on failure.
    """
    encoded_mailbox = urllib.parse.quote(mailbox_id, safe="")
    encoded_msg = urllib.parse.quote(original_message_id, safe="")
    create_url = (
        f"{GRAPH_ROOT}/users/{encoded_mailbox}/messages/{encoded_msg}/createReply"
    )

    try:
        resp = client.post(create_url, json_body={})
        resp.raise_for_status()
        draft = resp.json()
        draft_id = draft.get("id")
        if not draft_id:
            logger.warning("createReply did not return a message id for %s", original_message_id)
            return None
    except Exception as exc:
        logger.warning("Failed to create reply draft for message %s: %s", original_message_id, exc)
        return None

    patch_url = (
        f"{GRAPH_ROOT}/users/{encoded_mailbox}/messages/{urllib.parse.quote(draft_id, safe='')}"
    )
    patch_body = {
        "body": {
            "contentType": "HTML",
            "content": draft_body_html,
        }
    }
    try:
        resp = client.patch(patch_url, json_body=patch_body)
        resp.raise_for_status()
        return draft_id
    except Exception as exc:
        logger.warning("Failed to patch draft body for draft %s: %s", draft_id, exc)
        return None
